trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Configure Outerbounds'
  inputs:
    azureSubscription: 'dev-ob'
    addSpnToEnvironment: true
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      python -m pip install -U 'outerbounds[azure]' ob-project-utils
      outerbounds service-principal-configure \
        --from-obproject-toml \
        --toml-path obproject_multi.toml \
        --jwt-token $idToken

- script: |
    obproject-deploy
  displayName: 'Deploy Project'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    PYTHONUNBUFFERED: 1
    BUILD_SOURCEBRANCH: $(Build.SourceBranch)
    SYSTEM_PULLREQUEST_SOURCEBRANCH: $(System.PullRequest.SourceBranch)
    SYSTEM_COLLECTIONURI: $(System.CollectionUri)
    SYSTEM_TEAMPROJECT: $(System.TeamProject)
    BUILD_REPOSITORY_NAME: $(Build.Repository.Name)
    BUILD_REPOSITORY_ID: $(Build.Repository.ID)
    BUILD_BUILDID: $(Build.BuildId)
    SYSTEM_PULLREQUEST_PULLREQUESTID: $(System.PullRequest.PullRequestId)
